spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/deal
    username: postgres
    password: 0990
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show_sql: true
  main:
    web-application-type: servlet
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092


server:
  port: 8081

app:
  base-url: http://localhost:8080/calculator/