spring:

  datasource:
      url: jdbc:postgresql://localhost:5432/deal
      username: postgres
      password: 0990
      driverClassName: org.postgresql.Driver
      ddl-auto: create-drop

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create-drop
