version: '3'

services:
    postgres:
        image: 'postgres:16'
        env_file:
            - postgres.env
        ports:
            -   '5433:5432'
        volumes:
            - postgres_volume:/var/lib/postgresql/data


    zookeeper:
        image: confluentinc/cp-zookeeper:7.4.4
        ports:
            - "22181:2181"
        env_file:
            - .env
    kafka:
        image: confluentinc/cp-kafka:7.4.4
        depends_on:
            - zookeeper
        ports:
            - "9093:9093"
            - "9092:9092"
        env_file:
            - .env
        volumes:
            -   kafka_logs:/kafka/logs



volumes:
    postgres_volume:
        driver: local
    kafka_logs:
        driver: local