version: '3'

services:
    postgres:
        image: 'postgres:16'
        env_file:
            - postgres.env
        ports:
            -   '5433:5432'
        volumes:
            - postgres_volume:/var/lib/postgresql/data

volumes:
    postgres_volume:
        driver: local