spring:
  kafka:
    consumer:
      enable-auto-commit: true
      bootstrap-servers: localhost:9092
      group-id: bank_consumer_group
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer




  mail:
    host: smtp.gmail.com
    port: 587
    username: shchegolevilya1@gmail.com
    password: yrsiqgzwiiugfgvi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8083


